### ISSUE TITLE
call.client.ping; does not update every message (frequently)

### ISSUE THREAD

**Issue by gt-c** [cloewen8/Bro-Time-Server#43]
If you repeat /ping the ping will stay the same for a period of time around 10-20 seconds before actually having the ping return a different value

**Comment by cloewen8** [comment]
This is a Discord.JS related issue. The ping command uses the client's ping. If you believe that this behaviour is unintended, please create a new issue for [https://github.com/discordjs/discord.js](https://github.com/discordjs/discord.js).
