### ISSUE TITLE
Commands are caps sensitive

### ISSUE THREAD

**Issue by cloewen8** [cloewen8/Bro-Time-Server#64]
Commands can not be called with a difference case.

`ping` works, `Ping` does not work.

**Comment by gt-c** [comment]
not as much of a bug as a feature, how ever I don't see why this is necassary

**Comment by cloewen8** [comment]
I have seen a user break their caps lock before, so ignoring the case of a command could be valuable. I would like to know why you consider it a feature.

**Comment by cloewen8** [comment]
Commands have been made case insensitive.
